FROM openjdk:17-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the specific jar file from the target directory into the container
COPY target/Produits-0.0.1-SNAPSHOT.jar /app/ProduitService.jar

# Expose the port your application runs on
EXPOSE 8085

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "ProduitService.jar"]
